### ISSUE TITLE
error while running script

### ISSUE THREAD

**Issue by Abhi93696** [robertpro/pluralsight-videos-rename#1]
i m getting this error plz help!

<img width="403" alt="error" src="https://cloud.githubusercontent.com/assets/25771424/25522569/06f94ad4-2c21-11e7-8e52-75ec7242e77c.PNG">

**Comment by robertpro** [comment]
Can you show the directory contents ?

That error means that the script is not finding the json file

**Comment by Abhi93696** [comment]
Thanks 4 the reply!
According to me , json file is present in the directory...
Here's the dir-:
<img width="960" alt="dir" src="https://cloud.githubusercontent.com/assets/25771424/25538876/0eeea7e8-2c62-11e7-9d85-d8a46ecc2ff4.PNG">
Also file is not corrupted also-:
<img width="641" alt="dir2" src="https://cloud.githubusercontent.com/assets/25771424/25538897/2d237d9c-2c62-11e7-9013-3b318bbbab52.PNG">

BR

**Comment by robertpro** [comment]
Ohh I see, please rename your json file from json to ANYTHING.json

It should work 😉

**Comment by Abhi93696** [comment]
Now Working!! Thanks 4 the help!
